### ISSUE TITLE
Container auto crashing

### ISSUE THREAD

**Issue by cactusrent** [smilebasti/npmGrafStats#9]
Hello, upon starting up the npmgrafstats container it seems to be auto crashing immediately with the following logs posted:
```
Startup: lets get logs data and send them to influx
Redirection Logs activated
tail: cannot open '/logs/proxy-host-*_access.log' for reading: No such file or directory
tail: no files remaining
/root/.config/NPMGRAF/sendips.sh: line 38: reboot: command not found
```

I was just wondering if there is something I'm clearly doing wrong to get this started. Weirdly it kept looping a French IP address over and over again in the logs (possible it was looping through one entry?)

Attaching my config below----------

**Redacted npmgrafstats docker-compose:**
```
version: '3.8'
services:

  npmgraf:
    image: smilebasti/npmgrafstats:latest
    restart: unless-stopped
    environment:
      HOME_IPS: 'externalIP'
      REDIRECTION_LOGS: 'TRUE' # TRUE or FALSE
      INFLUX_HOST: 'hostip:8086' # use host IP
      INFLUX_BUCKET: 'npmgrafstats'
      INFLUX_ORG: 'npmgrafstats'
      INFLUX_TOKEN: 'cooltokennumber' # insert after first run and manual token creation
    volumes:
      - /data/compose/1/data/logs:/logs #nginx log location
      - ./geolite:/geolite
     
  influxdb:
    image: influxdb:2.7-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: 'setup'
      DOCKER_INFLUXDB_INIT_USERNAME: 'CoolUserName'
      DOCKER_INFLUXDB_INIT_PASSWORD: 'coolpassword' # atleast 8 characters
      DOCKER_INFLUXDB_INIT_ORG: 'npmgrafstats'
      DOCKER_INFLUXDB_INIT_BUCKET: 'npmgrafstats'
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdbv2:/var/lib/influxdb2
    ports:
      - '8086:8086'

  geoipupdate:
    image: maxmindinc/geoipupdate
    environment:
      GEOIPUPDATE_ACCOUNT_ID: 'accountid'
      GEOIPUPDATE_LICENSE_KEY: 'geoiplicense'
      GEOIPUPDATE_EDITION_IDS: 'GeoLite2-City'
      GEOIPUPDATE_FREQUENCY: 24
    volumes:
      - ./geolite:/usr/share/GeoIP
 ```
